<?php

namespace EcoJob\MessagerieBundle\Repository;

/**
 * SubMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
