eco_job_main_index:
    path:     /cachee
    defaults: { _controller: "EcoJobAnonymousBundle:Default:doSearch" }
    methods:  [GET,POST] 
    
eco_job_candidat_index:
    path:     /candidat.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:index" }
    methods:  GET

eco_job_recruteur_index:
    path:     /recruteur.php
    defaults: { _controller: "EcoJobRecruteurBundle:Recruteur:index" }
    methods:  GET
     
eco_job_anonymous_map:
    path:     /map.php
    defaults: { _controller: EcoJobAnonymousBundle:Default:map }   
    
eco_job_anonymous_offre_search:
    path:     /offres/filtering
    defaults: { _controller: "EcoJobAnonymousBundle:Default:search" }
    methods:  POST
    options: 
        expose:  true   
    
eco_job_anonymous__offre_searchpage:
    path:     /recherche.php
    defaults: { _controller: "EcoJobAnonymousBundle:Default:doSearch"}
    methods:  [GET,POST]     

eco_job_anonymous_offre:
    path:     /offre/{id}/show
    defaults: { _controller: "EcoJobAnonymousBundle:Default:showOffre" }
    methods:  [GET,POST]    
    

eco_job_anonymous_offre_details:
    path:     /offre/{id}/details
    defaults: { _controller: "EcoJobAnonymousBundle:Default:detailsOffre" }
    methods:  [GET,POST]
    options: 
        expose:  true  
        
eco_job_anonymous_offres_json:
    path:     /offres/gets/json
    defaults: { _controller: "EcoJobAnonymousBundle:Default:getAllJson" }
    methods:  [GET,POST]
    options: 
        expose:  true  
        
eco_job_anonymous_offre_search_ajax:
    path:     /offre/search_ajax
    defaults: { _controller: "EcoJobAnonymousBundle:Default:searchAjax" }
    methods:  [GET,POST]    
    options: 
        expose:  true    
eco_job_anonymous_offre_search_ajax_templated:
    path:     /offre/search_ajax/templated
    defaults: { _controller: "EcoJobAnonymousBundle:Default:searchAjaxTemplated" }
    methods:  [GET,POST]    
    options: 
        expose:  true   
eco_job_anonymous_offre_integralite:
    path:     /offre/{localisation}/{id}
    defaults: { _controller: "EcoJobAnonymousBundle:Default:integraliteOffre",localisation: "Lyon, France" }
    methods:  [GET,POST]