fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        ecojob:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: French
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_french_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                offre :
                    mappings:
                        recruteur :
                            index : not_analyzed
                        contrat : ~         
                        experience: ~
                        contenu :
                            index_analyzer : custom_analyzer
                            search_analyzer : custom_search_analyzer
                        titre:
                            boost: 6
                            index_analyzer : custom_analyzer
                            search_analyzer : custom_search_analyzer
                    persistence:
                        driver: orm
                        model_to_elastica_transformer:
                            service: ecojob.transformers.elastica.recruteur                      
                        model: EcoJob\RecruteurBundle\Entity\Offre
                        finder: ~
                        provider: ~
                        listener: ~
                    _parent:
                        type : "contrat"
                        identifier: "id"
                        property : "contrat"
