<?php

namespace EcoJob\RecruteurBundle\Repository;

/**
 * ContratTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
