<?php

namespace EcoJob\RecruteurBundle\Repository;

/**
 * ContratTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratCategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewOfferCategorie(){
        $hier = date('Y-m-d',  strtotime('-1 days'));
        $qb = $this->createQueryBuilder('cc')->distinct()
                   ->join('cc.offres','o')
                   ->where('DATE_FORMAT(o.validAt,\'%Y-%m-%d\') = :hier');
        $qb->setParameter('hier', $hier);
        return $qb->getQuery()
            	  ->getResult();
    }
}
