<?php

namespace EcoJob\RecruteurBundle\Repository;

/**
 * OffreSearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreSearchRepository extends \Doctrine\ORM\EntityRepository
{
}
