<?php

namespace EcoJob\CandidatBundle\Repository;

/**
 * CategorieFonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieFonctionRepository extends \Doctrine\ORM\EntityRepository
{
}
