<?php

namespace EcoJob\CandidatBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettreRepository extends \Doctrine\ORM\EntityRepository
{
}
