<?php

namespace EcoJob\CandidatBundle\Repository;

/**
 * NiveauFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
