<?php

namespace EcoJob\CandidatBundle\Repository;

/**
 * ParamCandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamCandidatRepository extends \Doctrine\ORM\EntityRepository
{
}
