<?php

namespace EcoJob\CandidatBundle\Repository;

/**
 * TypeClienteleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeClienteleRepository extends \Doctrine\ORM\EntityRepository
{
}
