<?php

namespace EcoJob\CandidatBundle\Repository;

/**
 * TypeRemunerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRemunerationRepository extends \Doctrine\ORM\EntityRepository
{
}
