eco_job_candidat_cv_fill:
    path:     /creer-cv.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:Fill"}
    methods:  [GET,POST]

    
eco_job_candidat_cv_show:
    path:     /afficher-cv.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:Show" }
    methods:  [GET,POST]    
    
         
        
eco_job_candidat_cv_edit:
    path:     /modifier-cv.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:Edit" }
    methods:  [GET,POST] 
    
         
        
eco_job_candidat_cv_delete:
    path:     /supprimer-cv.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:Delete" }
    methods:  [GET,POST]   
    
eco_job_candidat_offre_postuler:
    path:     /postuler.php/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:postuler" }
    methods:  [POST,GET]
    options:
        expose:  true
eco_job_candidat_offre:
    path:     /{localisation}/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:showOffre" }
    methods:  [GET,POST]
    
                 

eco_job_candidat_offre_save:
    path:     /sauvegarder.php/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:save" }
    methods:  [GET,POST]
    
        
        
eco_job_candidat_offre_save_async:
    path:     /offre/{id}/saveAsync
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:saveAsync" }
    methods:  [GET,POST]
    options:
        expose:  true

eco_job_candidat_offre_delet:
    path:     /supprimer/offre/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:deleteOffre" }
    methods:  [GET,POST]  
    
eco_job_candidat_offre_delete:
    path:     /supprimer/offre/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:deleteOffre" }
    methods:  [GET,POST]              
    
eco_job_candidat_myoffres:
    path:     /sauvegardees.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:myOffres" }
    methods:  [GET,POST]
    
            

eco_job_offres:
    path:     /offres
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:map" }
    methods:  GET        
    
eco_job_candidat_offre_details_2:
    path:     /offre/details/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:detailsOffre2" }
    methods:  GET 
    
    
eco_job_candidat_param:
    path: /parametre-email
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:Param" }
    methods:  [GET,POST]
    
eco_job_candidat_alert_mail:
    path:     /alert-mail
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:alertMail" }
    methods:  GET
    
eco_job_candidat_uploadcv:
    path:     /upload/cv
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:uploadCV" }
    methods:  [GET,POST]

eco_job_candidat_postuled_offres:
    path:     /postulees.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:postuledOffres" }
    methods:  [GET,POST]
    
        
        
eco_job_candidat_cancel_postuled:
    path:     /postulation-annuler.php/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:cancelPosulation" }
    methods:  [GET,POST]
    
        
#endofmycode

eco_job_offres:
    path:     /offres
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:map" }
    methods:  GET        
    
eco_job_candidat_offre_details_2:
    path:     /offre/details/{id}
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:detailsOffre2" }
    methods:  GET 
    
eco_job_candidat_reset_param:
    path:     /reinitialiser.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:ResetParam" }
    methods:  GET
    
            
    
eco_job_candidat_gerercv:
    path:     /gerer-cv.php
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:gererCV" }
    methods:  GET
    
           
        
eco_job_candidat_gerercv_stop:
    path:     /gerer-cv.php/{id}/stop
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:stop" }
    methods:  GET    
    
           
        
eco_job_candidat_add_photo:
    path:     /cv/gestion/add/photo
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addPhoto" }
    methods:  POST
    options:
        expose: true

eco_job_candidat_add_candidature:
    path:     /cv/gestion/add/candidature
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addCandidature" }
    methods:  POST
    options:
        expose: true


eco_job_candidat_add_cvfile:
    path:     /cv/gestion/add/file
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addCVFile" }
    methods:  POST
    options:
        expose: true        
        
eco_job_candidat_add_et:
    path:     /cv/gestion/add/et
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addEt" }
    methods:  POST
    options:
        expose: true 
        
eco_job_candidat_add_formation:
    path:     /cv/gestion/add/formation
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addFormation" }
    methods:  POST
    options:
        expose: true        
eco_job_candidat_edit_formation:
    path:     /cv/gestion/edit/{id}/formation
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:editFormation" }
    methods:  [GET,POST]
    options:
        expose: true      
eco_job_candidat_delete_formation:
    path:     /cv/gestion/delete/{id}/formation
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:deleteFormation" }
    methods:  [GET,POST]
    options:
        expose: true             
eco_job_candidat_add_experience:
    path:     /cv/gestion/add/experience
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addExperience" }
    methods:  POST
    options:
        expose: true        
eco_job_candidat_edit_experience:
    path:     /cv/gestion/edit/{id}/experience
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:editExperience" }
    methods:  [GET,POST]
    options:
        expose: true 
eco_job_candidat_delete_experience:
    path:     /cv/gestion/delete/{id}/experience
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:deleteExperience" }
    methods:  [GET,POST]
    options:
        expose: true             
eco_job_candidat_add_langue:
    path:     /cv/gestion/add/langue
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addLangue" }
    methods:  [POST,GET]
    options:
        expose: true        
eco_job_candidat_edit_langue:
    path:     /cv/gestion/edit/{id}/langue
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:editLangue" }
    methods:  [GET,POST]
    options:
        expose: true    
eco_job_candidat_delete_langue:
    path:     /cv/gestion/delete/{id}/langue
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:deleteLangue" }
    methods:  [GET,POST]
    options:
        expose: true            
eco_job_candidat_add_competence:
    path:     /cv/gestion/add/competence
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:addCompetence" }
    methods:  [POST,GET]
    options:
        expose: true        
eco_job_candidat_edit_competence:
    path:     /cv/gestion/edit/{id}/competence
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:editCompetence" }
    methods:  [GET,POST]
    options:
        expose: true    
eco_job_candidat_delete_competence:
    path:     /cv/gestion/delete/{id}/competence
    defaults: { _controller: "EcoJobCandidatBundle:Candidat:deleteCompetence" }
    methods:  [GET,POST]
    options:
        expose: true         