<?php

namespace EcoJob\UserBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewlyCandidat() 
    {
        $dateMax = new DateTime();
        $dateMin = $dateMax->modify('-2 day');
        $qb = $this->_em->createQuery("SELECT u FROM EcoJobUserBundle:User u");
        $qb->where('u.createdAt BETWEEN :dateMin AND :dateMax')
           ->setParameter('dateMin', $dateMin)
           ->setParameter('dateMax', $dateMax);

        return $query->getQQuery()->getResult();               
    }    
}
